#!/usr/bin/env bash
# kills the infinity and beyond  program using sigkill signal

# Get the pid of the program
id=$(pgrep -f "./4-to_infinity_and_beyond")

# Terminate the infinate process
kill -15 "$id"
